"""access_token_nullable

Revision ID: 32048d7dc697
Revises: e4ac1320bd8e
Create Date: 2025-02-28 17:49:48.418004

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "32048d7dc697"
down_revision: Union[str, None] = "e4ac1320bd8e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "UserProfile", "access_token", existing_type=sa.VARCHAR(), nullable=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "UserProfile", "access_token", existing_type=sa.VARCHAR(), nullable=False
    )
    # ### end Alembic commands ###
