"""access_token_taken_out

Revision ID: 645b3a3d8966
Revises: 32048d7dc697
Create Date: 2025-02-28 18:06:37.591778

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "645b3a3d8966"
down_revision: Union[str, None] = "32048d7dc697"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("UserProfile", "access_token")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "UserProfile",
        sa.Column("access_token", sa.VARCHAR(), autoincrement=False, nullable=True),
    )
    # ### end Alembic commands ###
