"""user_id_added_into_Tasks

Revision ID: de0fa552eaad
Revises: 645b3a3d8966
Create Date: 2025-02-28 19:00:33.708549

"""

from typing import Sequence, Union


# revision identifiers, used by Alembic.
revision: str = "de0fa552eaad"
down_revision: Union[str, None] = "645b3a3d8966"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
