"""ref-user-profile

Revision ID: f60ee9de67e2
Revises: 748ce7289445
Create Date: 2025-03-03 19:22:53.677859

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "f60ee9de67e2"
down_revision: Union[str, None] = "748ce7289445"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "UserProfile", "username", existing_type=sa.VARCHAR(), nullable=True
    )
    op.alter_column(
        "UserProfile", "password", existing_type=sa.VARCHAR(), nullable=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "UserProfile", "password", existing_type=sa.VARCHAR(), nullable=False
    )
    op.alter_column(
        "UserProfile", "username", existing_type=sa.VARCHAR(), nullable=False
    )
    # ### end Alembic commands ###
